import AsyncStorage from "@react-native-async-storage/async-storage";
import * as Localization from "expo-localization";
import { useColorScheme } from "nativewind";
import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from "react";

export type AppTheme = "light" | "dark" | "system";
export type AppLanguage = "pt-BR" | "en-US" | "es";

type TranslationParams = Record<string, string | number>;

interface AppPreferencesContextValue {
  theme: AppTheme;
  language: AppLanguage;
  isDark: boolean;
  setTheme: (theme: AppTheme) => Promise<void>;
  setLanguage: (language: AppLanguage) => Promise<void>;
  t: (key: string, params?: TranslationParams) => string;
}

const STORAGE_KEY = "@lokaro.preferences.v1";

const dictionaries: Record<AppLanguage, Record<string, string>> = {
  "pt-BR": {
    "brand.name": "Lokaro",
    "tabs.dashboard": "Dashboard",
    "tabs.members": "Membros",
    "tabs.bookings": "Reservas",
    "tabs.finance": "Financeiro",
    "tabs.settings": "Ajustes",
    "tabs.home": "Início",
    "tabs.book": "Reservar",
    "tabs.myBookings": "Minhas Reservas",
    "tabs.profile": "Perfil",
    "auth.welcome.title": "Lokaro",
    "auth.welcome.subtitle": "Gerencie membros, reservas e cobranças do seu espaço em um único lugar.",
    "auth.welcome.signup": "Criar conta",
    "auth.welcome.login": "Já tenho conta",
    "auth.login.title": "Bem-vindo de volta",
    "auth.login.subtitle": "Entre na sua conta",
    "auth.login.submit": "Entrar",
    "auth.login.signup": "Não tenho conta, criar agora",
    "auth.signup.title": "Criar conta",
    "auth.signup.subtitle": "Leva menos de um minuto",
    "auth.signup.submit": "Criar conta",
    "auth.signup.login": "Já tenho conta, entrar",
    "dashboard.greeting.morning": "Bom dia",
    "dashboard.greeting.afternoon": "Boa tarde",
    "dashboard.greeting.evening": "Boa noite",
    "dashboard.activeMembers": "Membros ativos",
    "dashboard.todayBookings": "Reservas hoje",
    "dashboard.activeRooms": "Salas ativas",
    "dashboard.pendingInvoices": "Faturas pendentes",
    "dashboard.heroKicker": "Painel do dia",
    "dashboard.heroDesc": "Veja rapidamente o que precisa de atenção e entre nas áreas principais com um toque.",
    "dashboard.ctaBookings": "Abrir reservas",
    "dashboard.ctaMembers": "Ver membros",
    "dashboard.focus": "Em foco hoje",
    "dashboard.membersHint": "Base ativa do espaço",
    "dashboard.roomsHint": "Espaços prontos para reservar",
    "dashboard.bookingsEmpty": "Nenhuma reserva confirmada para hoje.",
    "dashboard.bookingsSingle": "1 reserva confirmada para hoje.",
    "dashboard.bookingsMany": "{count} reservas confirmadas para hoje.",
    "dashboard.invoicesEmpty": "Nenhuma fatura pendente no momento.",
    "dashboard.invoicesSingle": "1 fatura precisa de atenção.",
    "dashboard.invoicesMany": "{count} faturas precisam de atenção.",
    "dashboard.nextSteps": "Próximos passos",
    "dashboard.nextStepsDesc": "Acompanhe a operação diária nas abas Membros, Reservas, Financeiro e Ajustes para manter tudo organizado.",
    "settings.title": "Ajustes",
    "settings.subtitle": "Preferências do espaço",
    "settings.branding": "Identidade da marca",
    "settings.brandingDesc": "Use uma identidade visual consistente para transmitir profissionalismo.",
    "settings.spaceName": "Nome do espaço",
    "settings.logoUrl": "Logo (URL)",
    "settings.appearance": "Aparência",
    "settings.theme": "Tema",
    "settings.theme.system": "Automático",
    "settings.theme.systemDynamic": "Automático ({current})",
    "settings.theme.light": "Claro manual",
    "settings.theme.dark": "Escuro manual",
    "settings.theme.currentLight": "claro",
    "settings.theme.currentDark": "escuro",
    "settings.theme.systemHelp": "Sistema segue o tema do aparelho ou navegador. Agora: {current}.",
    "settings.language": "Idioma",
    "settings.language.pt-BR": "Português (Brasil)",
    "settings.language.en-US": "English",
    "settings.language.es": "Español",
    "settings.timezone": "Fuso horário",
    "settings.currency": "Moeda",
    "settings.loggedAccount": "Conta logada",
    "settings.persistence": "As configurações do espaço são salvas no Supabase. Tema e idioma ficam salvos no dispositivo.",
    "settings.save": "Salvar configurações",
    "settings.discard": "Descartar alterações",
    "common.signOut": "Sair da conta",
    "profile.title": "Perfil",
    "profile.name": "Nome",
    "profile.email": "Email",
    "profile.space": "Espaço",
    "profile.status": "Status",
    "members.title": "Membros",
    "members.subtitle": "Gerencie os membros do espaço",
    "members.search": "Buscar por nome ou email",
    "members.filter.all": "Todos",
    "members.filter.active": "Ativos",
    "members.filter.trial": "Trial",
    "members.filter.overdue": "Inadimplentes",
    "members.filter.inactive": "Inativos",
    "members.empty.none": "Nenhum membro ainda",
    "members.empty.filtered": "Nenhum membro encontrado",
    "members.empty.noneDesc": "Toque no botão + para adicionar seu primeiro membro.",
    "members.empty.filteredDesc": "Tente ajustar os filtros de busca.",
    "bookings.title": "Reservas",
    "bookings.subtitle": "Agenda e salas do espaço",
    "bookings.tab.agenda": "Agenda",
    "bookings.tab.rooms": "Salas",
    "bookings.empty.filtered": "Nenhuma reserva para os filtros",
    "bookings.empty.filteredDesc": "Ajuste os filtros ou toque no botão + para criar uma reserva.",
    "bookings.empty.rooms": "Nenhuma sala cadastrada",
    "bookings.empty.roomsDesc": "Toque no botão + para criar sua primeira sala ou mesa.",
    "finance.title": "Financeiro",
    "finance.subtitle": "Faturas, planos e receita",
    "finance.newInvoice": "Nova fatura",
    "finance.generateAuto": "Gerar automático",
    "finance.cleanup": "Limpar duplicadas",
    "finance.pending": "Pendentes",
    "finance.overdue": "Atrasadas",
    "finance.paid": "Pagas",
    "finance.empty": "Nenhuma fatura encontrada",
    "finance.emptyDesc": "Cadastre planos ou gere cobranças para ver as faturas aqui.",
    "badge.active": "Ativo",
    "badge.trial": "Trial",
    "badge.overdue": "Inadimplente",
    "badge.inactive": "Inativo",
    "revenue.title": "Faturamento",
    "revenue.today": "Hoje",
    "revenue.week": "7 dias",
    "revenue.month": "Este mês",
    "revenue.receivedToday": "recebido hoje",
    "revenue.receivedWeek": "recebido nos últimos 7 dias",
    "revenue.receivedMonth": "recebido neste mês",
    "room.modal.new": "Nova sala",
    "room.modal.edit": "Editar sala",
    "room.modal.save": "Salvar alterações",
    "room.modal.create": "Criar sala",
    "member.modal.new": "Adicionar membro",
    "member.modal.edit": "Editar membro",
    "member.modal.save": "Salvar alterações",
    "member.modal.create": "Adicionar membro",
    "booking.modal.new": "Nova reserva",
    "booking.modal.confirm": "Confirmar reserva",
    "common.attention": "Atenção",
    "common.error": "Erro",
    "common.success": "Sucesso",
    "common.cancel": "Cancelar",
    "common.back": "Voltar",
    "common.continue": "Continuar",
    "common.holdToCancel": "segure p/\ncancelar",
    "auth.login.fillFields": "Preencha email e senha.",
    "auth.login.invalid": "Email ou senha incorretos.",
    "auth.signup.fillFields": "Preencha todos os campos.",
    "auth.signup.shortPassword": "A senha precisa ter pelo menos 6 caracteres.",
    "auth.signup.mismatch": "As senhas não conferem.",
    "auth.signup.confirmEmailTitle": "Confirme seu email",
    "auth.signup.confirmEmailDesc": "Enviamos um link de confirmação para o seu email. Confirme e depois faça login.",
    "auth.signup.name": "Nome completo",
    "auth.signup.namePlaceholder": "Seu nome",
    "auth.password": "Senha",
    "auth.confirmPassword": "Confirmar senha",
    "auth.passwordPlaceholder": "Mínimo 6 caracteres",
    "auth.confirmPlaceholder": "Repita a senha",
    "auth.yourPassword": "Sua senha",
    "onboarding.step1Title": "Qual é o nome do seu espaço?",
    "onboarding.step1Desc": "É assim que seus membros vão te encontrar.",
    "onboarding.spaceName": "Nome do espaço",
    "onboarding.spaceNamePlaceholder": "Ex: Hub Central Coworking",
    "onboarding.nameTooShort": "Digite um nome com pelo menos 3 letras.",
    "onboarding.step2Title": "Em qual fuso horário?",
    "onboarding.step2Desc": "As reservas usarão esse horário.",
    "onboarding.step3Title": "Qual moeda você usa?",
    "onboarding.step3Desc": "Para planos, faturas e relatórios.",
    "onboarding.finish": "Criar meu espaço 🚀",
    "onboarding.error": "Não foi possível criar o espaço. Tente novamente.",
    "memberBook.subtitle": "Salas e mesas disponíveis",
    "memberBook.empty": "Reservas em breve",
    "memberBook.emptyDesc": "Escolher sala, horário e confirmar em segundos.",
    "myBookings.subtitle": "Histórico e próximas",
    "myBookings.empty": "Você ainda não tem reservas",
    "myBookings.emptyDesc": "Suas reservas confirmadas e o histórico aparecem aqui.",
    "bookings.cancelTitle": "Cancelar reserva",
    "bookings.cancelMsg": "Tem certeza que deseja cancelar?",
    "roomType.meeting_room": "Sala de reunião",
    "roomType.hot_desk": "Hot desk",
    "roomType.private_office": "Escritório privativo",
    "room.person": "pessoa",
    "room.people": "pessoas",
    "room.active": "Ativa",
    "room.inactive": "Inativa",
    "room.name": "Nome *",
    "room.namePlaceholder": "Ex: \"Sala Azul\" ou \"Mesa 01\"",
    "room.type": "Tipo",
    "room.capacity": "Capacidade",
    "room.pricePerHour": "Preço/hora",
    "room.pricePerMonth": "Preço/mês",
    "room.optional": "(opcional)",
    "room.color": "Cor no calendário",
    "room.businessHours": "Horário de funcionamento",
    "room.open24h": "Aberta 24 horas",
    "room.opensAt": "Abre às",
    "room.closesAt": "Fecha às",
    "room.isActive": "Sala ativa",
    "room.nameRequired": "Digite o nome da sala ou mesa.",
    "room.capacityInvalid": "Capacidade precisa ser 1 ou mais.",
    "room.saveError": "Não foi possível salvar a sala.",
    "room.hoursHelp": "Digite só os números (ex.: 6 vira 06:00, 2230 vira 22:30). Se fechar depois da meia-noite (ex.: abre 18:00, fecha 02:00), o app entende o horário noturno.",
    "member.name": "Nome completo *",
    "member.namePlaceholder": "Nome do membro",
    "member.email": "Email *",
    "member.emailPlaceholder": "membro@exemplo.com",
    "member.phone": "Telefone",
    "member.status": "Status",
    "member.nameRequired": "Digite o nome do membro.",
    "member.emailInvalid": "Digite um email válido.",
    "member.emailDupTitle": "Email já cadastrado",
    "member.emailDupDesc": "Já existe um membro com esse email neste espaço.",
    "member.saveError": "Não foi possível salvar. Tente novamente.",
    "booking.room": "Sala *",
    "booking.member": "Membro *",
    "booking.start": "Início (HH:MM) *",
    "booking.duration": "Duração",
    "duration.hours": "Horas",
    "duration.days": "Dias",
    "duration.months": "Meses",
    "booking.reminder": "Lembrete por email",
    "reminder.none": "Sem lembrete",
    "reminder.before": "{h}h antes",
    "booking.reminderHelp": "O membro recebe um email no endereço cadastrado, no tempo escolhido antes da reserva.",
    "booking.summary": "Resumo da reserva",
    "booking.summaryStart": "Início",
    "booking.summaryEnd": "Término",
    "booking.timeHelp": "Digite só os números: 8 vira 08:00, 930 vira 09:30, 1030 vira 10:30. Para 1 hora e meia, use 1,5 ou 1:30 em Horas. Reservas respeitam intervalo de segurança de 15 minutos.",
    "booking.chooseRoom": "Escolha uma sala.",
    "booking.chooseMember": "Escolha o membro.",
    "booking.noRooms": "Nenhuma sala cadastrada — crie uma na aba \"Salas\".",
    "booking.noMembers": "Nenhum membro elegível — inadimplentes e inativos não podem reservar.",
    "booking.conflictTitle": "Horário ocupado",
    "booking.conflictMsg": "Já existe uma reserva nessa sala nesse horário ou dentro do intervalo de segurança de 15 minutos. Escolha outro horário ou outra sala.",
    "booking.outsideTitle": "Fora do horário desta sala",
    "booking.outsideMsg": "Esta sala funciona de {open} às {close}. Ajuste o horário ou edite o funcionamento da sala na aba Salas.",
    "booking.pastTitle": "Reserva no passado",
    "booking.pastMsg": "Esse horário já passou. Se registrar mesmo assim, essa reserva pode entrar no faturamento automático como realizada. Deseja continuar?",
    "booking.pastConfirm": "Registrar mesmo assim",
    "booking.createError": "Não foi possível criar a reserva.",
    "finance.invoiceNoDesc": "Fatura sem descrição",
    "finance.dueDate": "Vencimento",
    "finance.client": "Cliente",
    "finance.origin": "Origem",
    "finance.markPaid": "Marcar paga",
    "finance.markPaidTitle": "Confirmar pagamento",
    "finance.markPaidMsg": "Deseja marcar esta fatura como paga?",
    "finance.markPaidConfirm": "Sim, marcar",
    "finance.periodLabel": "Período da geração automática",
    "finance.period.today": "Hoje",
    "finance.period.week": "Semana",
    "finance.period.month": "Mês",
    "finance.period.custom": "Personalizado",
    "finance.filter.all": "Todas",
    "finance.cleanupTitle": "Limpar duplicadas",
    "finance.cleanupMsg": "Vai manter apenas uma fatura por grupo e remover as repetidas. Deseja continuar?",
    "finance.cleanupConfirm": "Limpar",
    "invoiceStatus.paid": "Paga",
    "invoiceStatus.overdue": "Atrasada",
    "invoiceStatus.cancelled": "Cancelada",
    "invoiceStatus.pending": "Pendente",
    "finance.invoiceRef": "Fatura #{id}",
    "memberHome.empty": "Nenhuma reserva próxima",
    "memberHome.emptyDesc": "Suas próximas reservas aparecem aqui.",
    "bookings.filters": "Filtros",
    "bookings.allRooms": "Todas as salas",
    "bookings.allMembers": "Todos os membros",
    "bookings.dayOccupancy": "Ocupação do dia",
    "bookings.reserved": "reservados",
    "finance.noDueDate": "Sem vencimento",
    "bookings.tab.leases": "Contratos",
    "roomType.house": "Casa",
    "roomType.kitnet": "Kitnet",
    "roomType.apartment": "Apartamento",
    "lease.newTitle": "Novo contrato de aluguel",
    "lease.unit": "Imóvel / unidade *",
    "lease.tenant": "Inquilino *",
    "lease.monthlyRent": "Valor mensal do aluguel *",
    "lease.dueDay": "Dia do vencimento",
    "lease.dayN": "Dia {d}",
    "lease.otherDay": "Outro",
    "lease.autoInfo": "A fatura do aluguel é gerada automaticamente todo mês, 7 dias antes do vencimento, e o inquilino recebe um lembrete por email 3 dias antes de vencer.",
    "lease.create": "Criar contrato",
    "lease.chooseUnit": "Escolha o imóvel ou unidade.",
    "lease.rentInvalid": "Informe um valor mensal válido.",
    "lease.dueDayInvalid": "O dia de vencimento deve ser entre 1 e 28.",
    "lease.occupiedTitle": "Unidade ocupada",
    "lease.occupiedMsg": "Já existe um contrato ativo para esta unidade. Encerre-o antes de criar outro.",
    "lease.saveError": "Não foi possível criar o contrato.",
    "lease.endTitle": "Encerrar contrato",
    "lease.endMsg": "Encerrar o contrato de {unit}? As faturas futuras deixarão de ser geradas.",
    "lease.endConfirm": "Encerrar",
    "lease.ended": "Encerrado",
    "lease.active": "Ativo",
    "lease.dueEvery": "vence dia {d}",
    "lease.empty": "Nenhum contrato de aluguel",
    "lease.emptyDesc": "Toque no botão + para vincular um inquilino a uma casa, kitnet ou apartamento.",
    "lease.deleteTitle": "Excluir contrato",
    "lease.deleteMsg": "Excluir o contrato de {unit}? As faturas já geradas serão mantidas no Financeiro.",
    "lease.deleteConfirm": "Excluir",
    "room.deleteTitle": "Excluir unidade",
    "room.deleteMsg": "Excluir {name}? O histórico de reservas desta unidade também será excluído. Esta ação não pode ser desfeita.",
    "room.deleteError": "Não foi possível excluir a unidade.",
    "room.hasLeaseTitle": "Unidade com contrato ativo",
    "room.hasLeaseMsg": "Encerre ou exclua o contrato de aluguel desta unidade antes de excluí-la (aba Contratos).",
    "room.hasBookingsTitle": "Unidade com reservas futuras",
    "room.hasBookingsMsg": "Cancele as reservas futuras desta unidade antes de excluí-la (aba Agenda).",
    "room.cancelAndDeleteMsg": "Esta unidade tem {count} reserva(s) futura(s) — a próxima em {date}. Deseja cancelar todas as reservas futuras e excluir a unidade?",
    "room.cancelAndDeleteConfirm": "Cancelar tudo e excluir",
    "plan.name.free": "Plano Grátis",
    "plan.name.starter": "Plano Starter",
    "plan.name.pro": "Plano Pro",
    "plan.usage": "{used} de {limit} unidades usadas",
    "plan.usageUnlimited": "{used} unidades — ilimitado",
    "plan.upgradeCta": "Fazer upgrade",
    "plan.limitTitle": "Limite do plano atingido",
    "plan.limitMsg": "Seu plano atual permite até {limit} unidades. Faça upgrade para adicionar mais salas, casas e kitnets.",
    "sender.title": "Remetente dos emails",
    "sender.subtitle": "Como seus clientes veem quem enviou os lembretes",
    "sender.preview": "Ficará assim",
    "sender.save": "Salvar remetente",
    "sender.saved": "Remetente atualizado! Os próximos emails já saem com o novo nome.",
    "sender.invalid": "O nome deve ter entre 2 e 40 caracteres.",
    "sender.error": "Não foi possível salvar. Tente novamente.",
    "sender.locked": "No plano Grátis os emails saem como \"Lokaro\". Faça upgrade para usar o nome do seu espaço.",
    "logo.pick": "Escolher logo do aparelho",
    "logo.uploading": "Enviando...",
    "logo.uploaded": "Logo enviado! Não esqueça de tocar em Salvar.",
    "logo.error": "Não foi possível enviar a imagem. Tente novamente.",
    "logo.permission": "Permita o acesso às fotos para escolher o logo.",
    "logo.hint": "Escolha uma imagem da galeria — o app ajusta a resolução sozinho. Ou cole um link abaixo, se preferir.",
    "booking.summaryHint": "Preencha horário e duração válidos para ver início e término.",
    "member.deleteTitle": "Excluir membro",
    "member.deleteMsg": "Excluir {name}? O histórico de reservas e faturas dele também será excluído. Esta ação não pode ser desfeita.",
    "member.deleteError": "Não foi possível excluir o membro.",
    "member.hasLeaseTitle": "Membro com contrato ativo",
    "member.hasLeaseMsg": "Este membro é inquilino de um contrato ativo. Encerre o contrato antes de excluí-lo (aba Contratos).",
    "member.hasBookingsTitle": "Membro com reservas futuras",
    "member.hasBookingsMsg": "Cancele as reservas futuras deste membro antes de excluí-lo (aba Agenda).",
    "member.hasInvoicesTitle": "Membro com faturas pendentes",
    "member.hasInvoicesMsg": "Este membro tem faturas em aberto. Marque como pagas ou resolva no Financeiro antes de excluí-lo.",
  },
  "en-US": {
    "brand.name": "Lokaro",
    "tabs.dashboard": "Dashboard",
    "tabs.members": "Members",
    "tabs.bookings": "Bookings",
    "tabs.finance": "Finance",
    "tabs.settings": "Settings",
    "tabs.home": "Home",
    "tabs.book": "Book",
    "tabs.myBookings": "My Bookings",
    "tabs.profile": "Profile",
    "auth.welcome.title": "Lokaro",
    "auth.welcome.subtitle": "Manage members, bookings, and billing for your workspace in one place.",
    "auth.welcome.signup": "Create account",
    "auth.welcome.login": "I already have an account",
    "auth.login.title": "Welcome back",
    "auth.login.subtitle": "Sign in to your account",
    "auth.login.submit": "Sign in",
    "auth.login.signup": "Create a new account",
    "auth.signup.title": "Create account",
    "auth.signup.subtitle": "It takes less than a minute",
    "auth.signup.submit": "Create account",
    "auth.signup.login": "I already have an account",
    "dashboard.greeting.morning": "Good morning",
    "dashboard.greeting.afternoon": "Good afternoon",
    "dashboard.greeting.evening": "Good evening",
    "dashboard.activeMembers": "Active members",
    "dashboard.todayBookings": "Today's bookings",
    "dashboard.activeRooms": "Active rooms",
    "dashboard.pendingInvoices": "Pending invoices",
    "dashboard.heroKicker": "Today overview",
    "dashboard.heroDesc": "See what needs attention at a glance and jump into the main areas with one tap.",
    "dashboard.ctaBookings": "Open bookings",
    "dashboard.ctaMembers": "View members",
    "dashboard.focus": "In focus today",
    "dashboard.membersHint": "Current active base",
    "dashboard.roomsHint": "Spaces ready to be booked",
    "dashboard.bookingsEmpty": "No confirmed bookings for today.",
    "dashboard.bookingsSingle": "1 confirmed booking for today.",
    "dashboard.bookingsMany": "{count} confirmed bookings for today.",
    "dashboard.invoicesEmpty": "No pending invoices right now.",
    "dashboard.invoicesSingle": "1 invoice needs attention.",
    "dashboard.invoicesMany": "{count} invoices need attention.",
    "dashboard.nextSteps": "Next steps",
    "dashboard.nextStepsDesc": "Track your daily operation in Members, Bookings, Finance, and Settings.",
    "settings.title": "Settings",
    "settings.subtitle": "Workspace preferences",
    "settings.branding": "Brand identity",
    "settings.brandingDesc": "Use a consistent visual identity to communicate professionalism.",
    "settings.spaceName": "Workspace name",
    "settings.logoUrl": "Logo (URL)",
    "settings.appearance": "Appearance",
    "settings.theme": "Theme",
    "settings.theme.system": "Auto",
    "settings.theme.systemDynamic": "Auto ({current})",
    "settings.theme.light": "Manual light",
    "settings.theme.dark": "Manual dark",
    "settings.theme.currentLight": "light",
    "settings.theme.currentDark": "dark",
    "settings.theme.systemHelp": "System follows your device or browser theme. Right now: {current}.",
    "settings.language": "Language",
    "settings.language.pt-BR": "Portuguese (Brazil)",
    "settings.language.en-US": "English",
    "settings.timezone": "Time zone",
    "settings.currency": "Currency",
    "settings.loggedAccount": "Signed in account",
    "settings.persistence": "Workspace settings are saved in Supabase. Theme and language are saved on this device.",
    "settings.save": "Save settings",
    "settings.discard": "Discard changes",
    "common.signOut": "Sign out",
    "profile.title": "Profile",
    "profile.name": "Name",
    "profile.email": "Email",
    "profile.space": "Workspace",
    "profile.status": "Status",
    "members.title": "Members",
    "members.subtitle": "Manage workspace members",
    "members.search": "Search by name or email",
    "members.filter.all": "All",
    "members.filter.active": "Active",
    "members.filter.trial": "Trial",
    "members.filter.overdue": "Overdue",
    "members.filter.inactive": "Inactive",
    "members.empty.none": "No members yet",
    "members.empty.filtered": "No members found",
    "members.empty.noneDesc": "Tap + to add your first member.",
    "members.empty.filteredDesc": "Try adjusting your search filters.",
    "bookings.title": "Bookings",
    "bookings.subtitle": "Workspace schedule and rooms",
    "bookings.tab.agenda": "Schedule",
    "bookings.tab.rooms": "Rooms",
    "bookings.empty.filtered": "No bookings for current filters",
    "bookings.empty.filteredDesc": "Adjust filters or tap + to create a booking.",
    "bookings.empty.rooms": "No rooms created",
    "bookings.empty.roomsDesc": "Tap + to create your first room or desk.",
    "finance.title": "Finance",
    "finance.subtitle": "Invoices, plans, and revenue",
    "finance.newInvoice": "New invoice",
    "finance.generateAuto": "Generate automatically",
    "finance.cleanup": "Clean duplicates",
    "finance.pending": "Pending",
    "finance.overdue": "Overdue",
    "finance.paid": "Paid",
    "finance.empty": "No invoices found",
    "finance.emptyDesc": "Create plans or generate billing to see invoices here.",
    "badge.active": "Active",
    "badge.trial": "Trial",
    "badge.overdue": "Overdue",
    "badge.inactive": "Inactive",
    "revenue.title": "Revenue",
    "revenue.today": "Today",
    "revenue.week": "7 days",
    "revenue.month": "This month",
    "revenue.receivedToday": "received today",
    "revenue.receivedWeek": "received in the last 7 days",
    "revenue.receivedMonth": "received this month",
    "room.modal.new": "New room",
    "room.modal.edit": "Edit room",
    "room.modal.save": "Save changes",
    "room.modal.create": "Create room",
    "member.modal.new": "Add member",
    "member.modal.edit": "Edit member",
    "member.modal.save": "Save changes",
    "member.modal.create": "Add member",
    "booking.modal.new": "New booking",
    "booking.modal.confirm": "Confirm booking",
    "common.attention": "Attention",
    "common.error": "Error",
    "common.success": "Success",
    "common.cancel": "Cancel",
    "common.back": "Back",
    "common.continue": "Continue",
    "common.holdToCancel": "hold to\ncancel",
    "auth.login.fillFields": "Enter your email and password.",
    "auth.login.invalid": "Incorrect email or password.",
    "auth.signup.fillFields": "Fill in all fields.",
    "auth.signup.shortPassword": "Password must be at least 6 characters.",
    "auth.signup.mismatch": "Passwords do not match.",
    "auth.signup.confirmEmailTitle": "Confirm your email",
    "auth.signup.confirmEmailDesc": "We sent a confirmation link to your email. Confirm it and then sign in.",
    "auth.signup.name": "Full name",
    "auth.signup.namePlaceholder": "Your name",
    "auth.password": "Password",
    "auth.confirmPassword": "Confirm password",
    "auth.passwordPlaceholder": "At least 6 characters",
    "auth.confirmPlaceholder": "Repeat the password",
    "auth.yourPassword": "Your password",
    "onboarding.step1Title": "What is your workspace called?",
    "onboarding.step1Desc": "This is how your members will find you.",
    "onboarding.spaceName": "Workspace name",
    "onboarding.spaceNamePlaceholder": "E.g. Central Hub Coworking",
    "onboarding.nameTooShort": "Enter a name with at least 3 letters.",
    "onboarding.step2Title": "Which time zone?",
    "onboarding.step2Desc": "Bookings will use this time.",
    "onboarding.step3Title": "Which currency do you use?",
    "onboarding.step3Desc": "For plans, invoices, and reports.",
    "onboarding.finish": "Create my workspace 🚀",
    "onboarding.error": "Could not create the workspace. Please try again.",
    "memberBook.subtitle": "Available rooms and desks",
    "memberBook.empty": "Bookings coming soon",
    "memberBook.emptyDesc": "Pick a room and time, confirm in seconds.",
    "myBookings.subtitle": "History and upcoming",
    "myBookings.empty": "You have no bookings yet",
    "myBookings.emptyDesc": "Your confirmed bookings and history will appear here.",
    "bookings.cancelTitle": "Cancel booking",
    "bookings.cancelMsg": "Are you sure you want to cancel?",
    "roomType.meeting_room": "Meeting room",
    "roomType.hot_desk": "Hot desk",
    "roomType.private_office": "Private office",
    "room.person": "person",
    "room.people": "people",
    "room.active": "Active",
    "room.inactive": "Inactive",
    "room.name": "Name *",
    "room.namePlaceholder": "E.g. \"Blue Room\" or \"Desk 01\"",
    "room.type": "Type",
    "room.capacity": "Capacity",
    "room.pricePerHour": "Price/hour",
    "room.pricePerMonth": "Price/month",
    "room.optional": "(optional)",
    "room.color": "Calendar color",
    "room.businessHours": "Business hours",
    "room.open24h": "Open 24 hours",
    "room.opensAt": "Opens at",
    "room.closesAt": "Closes at",
    "room.isActive": "Room active",
    "room.nameRequired": "Enter the room or desk name.",
    "room.capacityInvalid": "Capacity must be 1 or more.",
    "room.saveError": "Could not save the room.",
    "room.hoursHelp": "Type digits only (e.g. 6 becomes 06:00, 2230 becomes 22:30). If it closes after midnight (e.g. opens 18:00, closes 02:00), the app understands overnight hours.",
    "member.name": "Full name *",
    "member.namePlaceholder": "Member name",
    "member.email": "Email *",
    "member.emailPlaceholder": "member@example.com",
    "member.phone": "Phone",
    "member.status": "Status",
    "member.nameRequired": "Enter the member's name.",
    "member.emailInvalid": "Enter a valid email.",
    "member.emailDupTitle": "Email already registered",
    "member.emailDupDesc": "A member with this email already exists in this workspace.",
    "member.saveError": "Could not save. Please try again.",
    "booking.room": "Room *",
    "booking.member": "Member *",
    "booking.start": "Start (HH:MM) *",
    "booking.duration": "Duration",
    "duration.hours": "Hours",
    "duration.days": "Days",
    "duration.months": "Months",
    "booking.reminder": "Email reminder",
    "reminder.none": "No reminder",
    "reminder.before": "{h}h before",
    "booking.reminderHelp": "The member receives an email at their registered address, at the chosen time before the booking.",
    "booking.summary": "Booking summary",
    "booking.summaryStart": "Start",
    "booking.summaryEnd": "End",
    "booking.timeHelp": "Type digits only: 8 becomes 08:00, 930 becomes 09:30, 1030 becomes 10:30. For an hour and a half, use 1.5 or 1:30 in Hours. Bookings keep a 15-minute safety buffer.",
    "booking.chooseRoom": "Choose a room.",
    "booking.chooseMember": "Choose a member.",
    "booking.noRooms": "No rooms yet — create one in the \"Rooms\" tab.",
    "booking.noMembers": "No eligible members — overdue and inactive members cannot book.",
    "booking.conflictTitle": "Time slot taken",
    "booking.conflictMsg": "There is already a booking for this room at this time or within the 15-minute safety buffer. Choose another time or room.",
    "booking.outsideTitle": "Outside this room's hours",
    "booking.outsideMsg": "This room operates from {open} to {close}. Adjust the time or edit the room's hours in the Rooms tab.",
    "booking.pastTitle": "Booking in the past",
    "booking.pastMsg": "This time has already passed. If you register it anyway, it may enter automatic billing as completed. Continue?",
    "booking.pastConfirm": "Register anyway",
    "booking.createError": "Could not create the booking.",
    "finance.invoiceNoDesc": "Invoice without description",
    "finance.dueDate": "Due date",
    "finance.client": "Client",
    "finance.origin": "Origin",
    "finance.markPaid": "Mark paid",
    "finance.markPaidTitle": "Confirm payment",
    "finance.markPaidMsg": "Mark this invoice as paid?",
    "finance.markPaidConfirm": "Yes, mark paid",
    "finance.periodLabel": "Automatic generation period",
    "finance.period.today": "Today",
    "finance.period.week": "Week",
    "finance.period.month": "Month",
    "finance.period.custom": "Custom",
    "finance.filter.all": "All",
    "finance.cleanupTitle": "Clean duplicates",
    "finance.cleanupMsg": "This keeps one invoice per group and removes the duplicates. Continue?",
    "finance.cleanupConfirm": "Clean",
    "invoiceStatus.paid": "Paid",
    "invoiceStatus.overdue": "Overdue",
    "invoiceStatus.cancelled": "Cancelled",
    "invoiceStatus.pending": "Pending",
    "finance.invoiceRef": "Invoice #{id}",
    "memberHome.empty": "No upcoming bookings",
    "memberHome.emptyDesc": "Your upcoming bookings will appear here.",
    "bookings.filters": "Filters",
    "bookings.allRooms": "All rooms",
    "bookings.allMembers": "All members",
    "bookings.dayOccupancy": "Day occupancy",
    "bookings.reserved": "reserved",
    "finance.noDueDate": "No due date",
    "bookings.tab.leases": "Leases",
    "roomType.house": "House",
    "roomType.kitnet": "Studio (kitnet)",
    "roomType.apartment": "Apartment",
    "lease.newTitle": "New rental lease",
    "lease.unit": "Property / unit *",
    "lease.tenant": "Tenant *",
    "lease.monthlyRent": "Monthly rent *",
    "lease.dueDay": "Due day",
    "lease.dayN": "Day {d}",
    "lease.otherDay": "Other",
    "lease.autoInfo": "The rent invoice is generated automatically every month, 7 days before the due date, and the tenant receives an email reminder 3 days before it is due.",
    "lease.create": "Create lease",
    "lease.chooseUnit": "Choose the property or unit.",
    "lease.rentInvalid": "Enter a valid monthly amount.",
    "lease.dueDayInvalid": "Due day must be between 1 and 28.",
    "lease.occupiedTitle": "Unit occupied",
    "lease.occupiedMsg": "There is already an active lease for this unit. End it before creating another.",
    "lease.saveError": "Could not create the lease.",
    "lease.endTitle": "End lease",
    "lease.endMsg": "End the lease for {unit}? Future invoices will stop being generated.",
    "lease.endConfirm": "End lease",
    "lease.ended": "Ended",
    "lease.active": "Active",
    "lease.dueEvery": "due on day {d}",
    "lease.empty": "No rental leases",
    "lease.emptyDesc": "Tap the + button to link a tenant to a house, studio, or apartment.",
    "lease.deleteTitle": "Delete lease",
    "lease.deleteMsg": "Delete the lease for {unit}? Invoices already generated will be kept in Finance.",
    "lease.deleteConfirm": "Delete",
    "room.deleteTitle": "Delete unit",
    "room.deleteMsg": "Delete {name}? This unit's booking history will also be deleted. This action cannot be undone.",
    "room.deleteError": "Could not delete the unit.",
    "room.hasLeaseTitle": "Unit has an active lease",
    "room.hasLeaseMsg": "End or delete this unit's rental lease before deleting it (Leases tab).",
    "room.hasBookingsTitle": "Unit has upcoming bookings",
    "room.hasBookingsMsg": "Cancel this unit's upcoming bookings before deleting it (Schedule tab).",
    "room.cancelAndDeleteMsg": "This unit has {count} upcoming booking(s) — the next one on {date}. Cancel all upcoming bookings and delete the unit?",
    "room.cancelAndDeleteConfirm": "Cancel all and delete",
    "plan.name.free": "Free plan",
    "plan.name.starter": "Starter plan",
    "plan.name.pro": "Pro plan",
    "plan.usage": "{used} of {limit} units used",
    "plan.usageUnlimited": "{used} units — unlimited",
    "plan.upgradeCta": "Upgrade",
    "plan.limitTitle": "Plan limit reached",
    "plan.limitMsg": "Your current plan allows up to {limit} units. Upgrade to add more rooms, houses, and studios.",
    "sender.title": "Email sender name",
    "sender.subtitle": "How your clients see who sent the reminders",
    "sender.preview": "It will look like",
    "sender.save": "Save sender",
    "sender.saved": "Sender updated! Upcoming emails will use the new name.",
    "sender.invalid": "Name must be between 2 and 40 characters.",
    "sender.error": "Could not save. Please try again.",
    "sender.locked": "On the Free plan emails are sent as \"Lokaro\". Upgrade to use your space's name.",
    "logo.pick": "Choose logo from device",
    "logo.uploading": "Uploading...",
    "logo.uploaded": "Logo uploaded! Don't forget to tap Save.",
    "logo.error": "Could not upload the image. Please try again.",
    "logo.permission": "Allow photo access to choose a logo.",
    "logo.hint": "Pick an image from your gallery — the app adjusts the resolution automatically. Or paste a link below if you prefer.",
    "booking.summaryHint": "Enter a valid time and duration to see start and end.",
    "member.deleteTitle": "Delete member",
    "member.deleteMsg": "Delete {name}? Their booking and invoice history will also be deleted. This action cannot be undone.",
    "member.deleteError": "Could not delete the member.",
    "member.hasLeaseTitle": "Member has an active lease",
    "member.hasLeaseMsg": "This member is the tenant of an active lease. End the lease before deleting them (Leases tab).",
    "member.hasBookingsTitle": "Member has upcoming bookings",
    "member.hasBookingsMsg": "Cancel this member's upcoming bookings before deleting them (Schedule tab).",
    "member.hasInvoicesTitle": "Member has pending invoices",
    "member.hasInvoicesMsg": "This member has open invoices. Mark them paid or resolve them in Finance before deleting.",
  },
  "es": {
    "brand.name": "Lokaro",
    "tabs.dashboard": "Panel",
    "tabs.members": "Miembros",
    "tabs.bookings": "Reservas",
    "tabs.finance": "Finanzas",
    "tabs.settings": "Ajustes",
    "tabs.home": "Inicio",
    "tabs.book": "Reservar",
    "tabs.myBookings": "Mis Reservas",
    "tabs.profile": "Perfil",
    "auth.welcome.title": "Lokaro",
    "auth.welcome.subtitle": "Gestiona miembros, reservas y cobros de tu espacio en un solo lugar.",
    "auth.welcome.signup": "Crear cuenta",
    "auth.welcome.login": "Ya tengo cuenta",
    "auth.login.title": "Bienvenido de nuevo",
    "auth.login.subtitle": "Entra en tu cuenta",
    "auth.login.submit": "Entrar",
    "auth.login.signup": "No tengo cuenta, crear ahora",
    "auth.signup.title": "Crear cuenta",
    "auth.signup.subtitle": "Toma menos de un minuto",
    "auth.signup.submit": "Crear cuenta",
    "auth.signup.login": "Ya tengo cuenta, entrar",
    "dashboard.greeting.morning": "Buenos días",
    "dashboard.greeting.afternoon": "Buenas tardes",
    "dashboard.greeting.evening": "Buenas noches",
    "dashboard.activeMembers": "Miembros activos",
    "dashboard.todayBookings": "Reservas hoy",
    "dashboard.activeRooms": "Salas activas",
    "dashboard.pendingInvoices": "Facturas pendientes",
    "dashboard.heroKicker": "Panel del día",
    "dashboard.heroDesc": "Ve rápido lo que necesita atención y entra en las áreas principales con un toque.",
    "dashboard.ctaBookings": "Abrir reservas",
    "dashboard.ctaMembers": "Ver miembros",
    "dashboard.focus": "En foco hoy",
    "dashboard.membersHint": "Base activa del espacio",
    "dashboard.roomsHint": "Espacios listos para reservar",
    "dashboard.bookingsEmpty": "No hay reservas confirmadas para hoy.",
    "dashboard.bookingsSingle": "1 reserva confirmada para hoy.",
    "dashboard.bookingsMany": "{count} reservas confirmadas para hoy.",
    "dashboard.invoicesEmpty": "No hay facturas pendientes en este momento.",
    "dashboard.invoicesSingle": "1 factura necesita atención.",
    "dashboard.invoicesMany": "{count} facturas necesitan atención.",
    "dashboard.nextSteps": "Próximos pasos",
    "dashboard.nextStepsDesc": "Sigue la operación diaria en las pestañas Miembros, Reservas, Finanzas y Ajustes para mantener todo organizado.",
    "settings.title": "Ajustes",
    "settings.subtitle": "Preferencias del espacio",
    "settings.branding": "Identidad de marca",
    "settings.brandingDesc": "Usa una identidad visual consistente para transmitir profesionalismo.",
    "settings.spaceName": "Nombre del espacio",
    "settings.logoUrl": "Logo (URL)",
    "settings.appearance": "Apariencia",
    "settings.theme": "Tema",
    "settings.theme.system": "Automático",
    "settings.theme.systemDynamic": "Automático ({current})",
    "settings.theme.light": "Claro manual",
    "settings.theme.dark": "Oscuro manual",
    "settings.theme.currentLight": "claro",
    "settings.theme.currentDark": "oscuro",
    "settings.theme.systemHelp": "Sistema sigue el tema del dispositivo o navegador. Ahora: {current}.",
    "settings.language": "Idioma",
    "settings.language.pt-BR": "Português (Brasil)",
    "settings.language.en-US": "English",
    "settings.language.es": "Español",
    "settings.timezone": "Zona horaria",
    "settings.currency": "Moneda",
    "settings.loggedAccount": "Cuenta conectada",
    "settings.persistence": "La configuración del espacio se guarda en Supabase. El tema y el idioma se guardan en el dispositivo.",
    "settings.save": "Guardar configuración",
    "settings.discard": "Descartar cambios",
    "common.signOut": "Cerrar sesión",
    "profile.title": "Perfil",
    "profile.name": "Nombre",
    "profile.email": "Email",
    "profile.space": "Espacio",
    "profile.status": "Estado",
    "members.title": "Miembros",
    "members.subtitle": "Gestiona los miembros del espacio",
    "members.search": "Buscar por nombre o email",
    "members.filter.all": "Todos",
    "members.filter.active": "Activos",
    "members.filter.trial": "Prueba",
    "members.filter.overdue": "Morosos",
    "members.filter.inactive": "Inactivos",
    "members.empty.none": "Aún no hay miembros",
    "members.empty.filtered": "Ningún miembro encontrado",
    "members.empty.noneDesc": "Toca el botón + para añadir tu primer miembro.",
    "members.empty.filteredDesc": "Prueba a ajustar los filtros de búsqueda.",
    "bookings.title": "Reservas",
    "bookings.subtitle": "Agenda y salas del espacio",
    "bookings.tab.agenda": "Agenda",
    "bookings.tab.rooms": "Salas",
    "bookings.empty.filtered": "Ninguna reserva para los filtros",
    "bookings.empty.filteredDesc": "Ajusta los filtros o toca el botón + para crear una reserva.",
    "bookings.empty.rooms": "Ninguna sala registrada",
    "bookings.empty.roomsDesc": "Toca el botón + para crear tu primera sala o escritorio.",
    "finance.title": "Finanzas",
    "finance.subtitle": "Facturas, planes e ingresos",
    "finance.newInvoice": "Nueva factura",
    "finance.generateAuto": "Generar automático",
    "finance.cleanup": "Limpiar duplicadas",
    "finance.pending": "Pendientes",
    "finance.overdue": "Vencidas",
    "finance.paid": "Pagadas",
    "finance.empty": "Ninguna factura encontrada",
    "finance.emptyDesc": "Registra planes o genera cobros para ver las facturas aquí.",
    "badge.active": "Activo",
    "badge.trial": "Prueba",
    "badge.overdue": "Moroso",
    "badge.inactive": "Inactivo",
    "revenue.title": "Ingresos",
    "revenue.today": "Hoy",
    "revenue.week": "7 días",
    "revenue.month": "Este mes",
    "revenue.receivedToday": "recibido hoy",
    "revenue.receivedWeek": "recibido en los últimos 7 días",
    "revenue.receivedMonth": "recibido este mes",
    "room.modal.new": "Nueva sala",
    "room.modal.edit": "Editar sala",
    "room.modal.save": "Guardar cambios",
    "room.modal.create": "Crear sala",
    "member.modal.new": "Añadir miembro",
    "member.modal.edit": "Editar miembro",
    "member.modal.save": "Guardar cambios",
    "member.modal.create": "Añadir miembro",
    "booking.modal.new": "Nueva reserva",
    "booking.modal.confirm": "Confirmar reserva",
    "common.attention": "Atención",
    "common.error": "Error",
    "common.success": "Éxito",
    "common.cancel": "Cancelar",
    "common.back": "Volver",
    "common.continue": "Continuar",
    "common.holdToCancel": "mantén p/\ncancelar",
    "auth.login.fillFields": "Completa email y contraseña.",
    "auth.login.invalid": "Email o contraseña incorrectos.",
    "auth.signup.fillFields": "Completa todos los campos.",
    "auth.signup.shortPassword": "La contraseña debe tener al menos 6 caracteres.",
    "auth.signup.mismatch": "Las contraseñas no coinciden.",
    "auth.signup.confirmEmailTitle": "Confirma tu email",
    "auth.signup.confirmEmailDesc": "Enviamos un enlace de confirmación a tu email. Confírmalo y luego inicia sesión.",
    "auth.signup.name": "Nombre completo",
    "auth.signup.namePlaceholder": "Tu nombre",
    "auth.password": "Contraseña",
    "auth.confirmPassword": "Confirmar contraseña",
    "auth.passwordPlaceholder": "Mínimo 6 caracteres",
    "auth.confirmPlaceholder": "Repite la contraseña",
    "auth.yourPassword": "Tu contraseña",
    "onboarding.step1Title": "¿Cómo se llama tu espacio?",
    "onboarding.step1Desc": "Así te encontrarán tus miembros.",
    "onboarding.spaceName": "Nombre del espacio",
    "onboarding.spaceNamePlaceholder": "Ej: Hub Central Coworking",
    "onboarding.nameTooShort": "Escribe un nombre con al menos 3 letras.",
    "onboarding.step2Title": "¿En qué zona horaria?",
    "onboarding.step2Desc": "Las reservas usarán ese horario.",
    "onboarding.step3Title": "¿Qué moneda usas?",
    "onboarding.step3Desc": "Para planes, facturas e informes.",
    "onboarding.finish": "Crear mi espacio 🚀",
    "onboarding.error": "No se pudo crear el espacio. Inténtalo de nuevo.",
    "memberBook.subtitle": "Salas y escritorios disponibles",
    "memberBook.empty": "Reservas muy pronto",
    "memberBook.emptyDesc": "Elegir sala, horario y confirmar en segundos.",
    "myBookings.subtitle": "Historial y próximas",
    "myBookings.empty": "Aún no tienes reservas",
    "myBookings.emptyDesc": "Tus reservas confirmadas y el historial aparecen aquí.",
    "bookings.cancelTitle": "Cancelar reserva",
    "bookings.cancelMsg": "¿Seguro que deseas cancelar?",
    "roomType.meeting_room": "Sala de reuniones",
    "roomType.hot_desk": "Hot desk",
    "roomType.private_office": "Oficina privada",
    "room.person": "persona",
    "room.people": "personas",
    "room.active": "Activa",
    "room.inactive": "Inactiva",
    "room.name": "Nombre *",
    "room.namePlaceholder": "Ej: \"Sala Azul\" o \"Escritorio 01\"",
    "room.type": "Tipo",
    "room.capacity": "Capacidad",
    "room.pricePerHour": "Precio/hora",
    "room.pricePerMonth": "Precio/mes",
    "room.optional": "(opcional)",
    "room.color": "Color en el calendario",
    "room.businessHours": "Horario de funcionamiento",
    "room.open24h": "Abierta 24 horas",
    "room.opensAt": "Abre a las",
    "room.closesAt": "Cierra a las",
    "room.isActive": "Sala activa",
    "room.nameRequired": "Escribe el nombre de la sala o escritorio.",
    "room.capacityInvalid": "La capacidad debe ser 1 o más.",
    "room.saveError": "No se pudo guardar la sala.",
    "room.hoursHelp": "Escribe solo los números (ej.: 6 se convierte en 06:00, 2230 en 22:30). Si cierra después de medianoche (ej.: abre 18:00, cierra 02:00), la app entiende el horario nocturno.",
    "member.name": "Nombre completo *",
    "member.namePlaceholder": "Nombre del miembro",
    "member.email": "Email *",
    "member.emailPlaceholder": "miembro@ejemplo.com",
    "member.phone": "Teléfono",
    "member.status": "Estado",
    "member.nameRequired": "Escribe el nombre del miembro.",
    "member.emailInvalid": "Escribe un email válido.",
    "member.emailDupTitle": "Email ya registrado",
    "member.emailDupDesc": "Ya existe un miembro con ese email en este espacio.",
    "member.saveError": "No se pudo guardar. Inténtalo de nuevo.",
    "booking.room": "Sala *",
    "booking.member": "Miembro *",
    "booking.start": "Inicio (HH:MM) *",
    "booking.duration": "Duración",
    "duration.hours": "Horas",
    "duration.days": "Días",
    "duration.months": "Meses",
    "booking.reminder": "Recordatorio por email",
    "reminder.none": "Sin recordatorio",
    "reminder.before": "{h}h antes",
    "booking.reminderHelp": "El miembro recibe un email en la dirección registrada, en el tiempo elegido antes de la reserva.",
    "booking.summary": "Resumen de la reserva",
    "booking.summaryStart": "Inicio",
    "booking.summaryEnd": "Fin",
    "booking.timeHelp": "Escribe solo los números: 8 se convierte en 08:00, 930 en 09:30, 1030 en 10:30. Para 1 hora y media, usa 1,5 o 1:30 en Horas. Las reservas respetan un intervalo de seguridad de 15 minutos.",
    "booking.chooseRoom": "Elige una sala.",
    "booking.chooseMember": "Elige el miembro.",
    "booking.noRooms": "Ninguna sala registrada — crea una en la pestaña \"Salas\".",
    "booking.noMembers": "Ningún miembro elegible — morosos e inactivos no pueden reservar.",
    "booking.conflictTitle": "Horario ocupado",
    "booking.conflictMsg": "Ya existe una reserva en esa sala en ese horario o dentro del intervalo de seguridad de 15 minutos. Elige otro horario u otra sala.",
    "booking.outsideTitle": "Fuera del horario de esta sala",
    "booking.outsideMsg": "Esta sala funciona de {open} a {close}. Ajusta el horario o edita el funcionamiento de la sala en la pestaña Salas.",
    "booking.pastTitle": "Reserva en el pasado",
    "booking.pastMsg": "Ese horario ya pasó. Si la registras igualmente, esta reserva puede entrar en la facturación automática como realizada. ¿Deseas continuar?",
    "booking.pastConfirm": "Registrar de todos modos",
    "booking.createError": "No se pudo crear la reserva.",
    "finance.invoiceNoDesc": "Factura sin descripción",
    "finance.dueDate": "Vencimiento",
    "finance.client": "Cliente",
    "finance.origin": "Origen",
    "finance.markPaid": "Marcar pagada",
    "finance.markPaidTitle": "Confirmar pago",
    "finance.markPaidMsg": "¿Deseas marcar esta factura como pagada?",
    "finance.markPaidConfirm": "Sí, marcar",
    "finance.periodLabel": "Período de la generación automática",
    "finance.period.today": "Hoy",
    "finance.period.week": "Semana",
    "finance.period.month": "Mes",
    "finance.period.custom": "Personalizado",
    "finance.filter.all": "Todas",
    "finance.cleanupTitle": "Limpiar duplicadas",
    "finance.cleanupMsg": "Se mantendrá solo una factura por grupo y se eliminarán las repetidas. ¿Deseas continuar?",
    "finance.cleanupConfirm": "Limpiar",
    "invoiceStatus.paid": "Pagada",
    "invoiceStatus.overdue": "Vencida",
    "invoiceStatus.cancelled": "Cancelada",
    "invoiceStatus.pending": "Pendiente",
    "finance.invoiceRef": "Factura #{id}",
    "memberHome.empty": "Ninguna reserva próxima",
    "memberHome.emptyDesc": "Tus próximas reservas aparecen aquí.",
    "bookings.filters": "Filtros",
    "bookings.allRooms": "Todas las salas",
    "bookings.allMembers": "Todos los miembros",
    "bookings.dayOccupancy": "Ocupación del día",
    "bookings.reserved": "reservados",
    "finance.noDueDate": "Sin vencimiento",
    "bookings.tab.leases": "Contratos",
    "roomType.house": "Casa",
    "roomType.kitnet": "Estudio",
    "roomType.apartment": "Apartamento",
    "lease.newTitle": "Nuevo contrato de alquiler",
    "lease.unit": "Inmueble / unidad *",
    "lease.tenant": "Inquilino *",
    "lease.monthlyRent": "Valor mensual del alquiler *",
    "lease.dueDay": "Día de vencimiento",
    "lease.dayN": "Día {d}",
    "lease.otherDay": "Otro",
    "lease.autoInfo": "La factura del alquiler se genera automáticamente cada mes, 7 días antes del vencimiento, y el inquilino recibe un recordatorio por email 3 días antes de vencer.",
    "lease.create": "Crear contrato",
    "lease.chooseUnit": "Elige el inmueble o unidad.",
    "lease.rentInvalid": "Indica un valor mensual válido.",
    "lease.dueDayInvalid": "El día de vencimiento debe estar entre 1 y 28.",
    "lease.occupiedTitle": "Unidad ocupada",
    "lease.occupiedMsg": "Ya existe un contrato activo para esta unidad. Finalízalo antes de crear otro.",
    "lease.saveError": "No se pudo crear el contrato.",
    "lease.endTitle": "Finalizar contrato",
    "lease.endMsg": "¿Finalizar el contrato de {unit}? Las facturas futuras dejarán de generarse.",
    "lease.endConfirm": "Finalizar",
    "lease.ended": "Finalizado",
    "lease.active": "Activo",
    "lease.dueEvery": "vence el día {d}",
    "lease.empty": "Ningún contrato de alquiler",
    "lease.emptyDesc": "Toca el botón + para vincular un inquilino a una casa, estudio o apartamento.",
    "lease.deleteTitle": "Eliminar contrato",
    "lease.deleteMsg": "¿Eliminar el contrato de {unit}? Las facturas ya generadas se mantendrán en Finanzas.",
    "lease.deleteConfirm": "Eliminar",
    "room.deleteTitle": "Eliminar unidad",
    "room.deleteMsg": "¿Eliminar {name}? El historial de reservas de esta unidad también se eliminará. Esta acción no se puede deshacer.",
    "room.deleteError": "No se pudo eliminar la unidad.",
    "room.hasLeaseTitle": "Unidad con contrato activo",
    "room.hasLeaseMsg": "Finaliza o elimina el contrato de alquiler de esta unidad antes de eliminarla (pestaña Contratos).",
    "room.hasBookingsTitle": "Unidad con reservas futuras",
    "room.hasBookingsMsg": "Cancela las reservas futuras de esta unidad antes de eliminarla (pestaña Agenda).",
    "room.cancelAndDeleteMsg": "Esta unidad tiene {count} reserva(s) futura(s) — la próxima el {date}. ¿Deseas cancelar todas las reservas futuras y eliminar la unidad?",
    "room.cancelAndDeleteConfirm": "Cancelar todo y eliminar",
    "plan.name.free": "Plan Gratis",
    "plan.name.starter": "Plan Starter",
    "plan.name.pro": "Plan Pro",
    "plan.usage": "{used} de {limit} unidades usadas",
    "plan.usageUnlimited": "{used} unidades — ilimitado",
    "plan.upgradeCta": "Mejorar plan",
    "plan.limitTitle": "Límite del plan alcanzado",
    "plan.limitMsg": "Tu plan actual permite hasta {limit} unidades. Mejora tu plan para añadir más salas, casas y estudios.",
    "sender.title": "Remitente de los emails",
    "sender.subtitle": "Cómo ven tus clientes quién envió los recordatorios",
    "sender.preview": "Se verá así",
    "sender.save": "Guardar remitente",
    "sender.saved": "¡Remitente actualizado! Los próximos emails ya saldrán con el nuevo nombre.",
    "sender.invalid": "El nombre debe tener entre 2 y 40 caracteres.",
    "sender.error": "No se pudo guardar. Inténtalo de nuevo.",
    "sender.locked": "En el plan Gratis los emails salen como \"Lokaro\". Mejora tu plan para usar el nombre de tu espacio.",
    "logo.pick": "Elegir logo del dispositivo",
    "logo.uploading": "Subiendo...",
    "logo.uploaded": "¡Logo subido! No olvides tocar Guardar.",
    "logo.error": "No se pudo subir la imagen. Inténtalo de nuevo.",
    "logo.permission": "Permite el acceso a las fotos para elegir el logo.",
    "logo.hint": "Elige una imagen de la galería — la app ajusta la resolución sola. O pega un enlace abajo, si prefieres.",
    "booking.summaryHint": "Completa un horario y una duración válidos para ver inicio y fin.",
    "member.deleteTitle": "Eliminar miembro",
    "member.deleteMsg": "¿Eliminar a {name}? Su historial de reservas y facturas también se eliminará. Esta acción no se puede deshacer.",
    "member.deleteError": "No se pudo eliminar el miembro.",
    "member.hasLeaseTitle": "Miembro con contrato activo",
    "member.hasLeaseMsg": "Este miembro es inquilino de un contrato activo. Finaliza el contrato antes de eliminarlo (pestaña Contratos).",
    "member.hasBookingsTitle": "Miembro con reservas futuras",
    "member.hasBookingsMsg": "Cancela las reservas futuras de este miembro antes de eliminarlo (pestaña Agenda).",
    "member.hasInvoicesTitle": "Miembro con facturas pendientes",
    "member.hasInvoicesMsg": "Este miembro tiene facturas abiertas. Márcalas como pagadas o resuélvelo en Finanzas antes de eliminarlo.",
  },
};

const AppPreferencesContext =
  createContext<AppPreferencesContextValue | undefined>(undefined);

interface StoredPreferences {
  theme: AppTheme;
  language: AppLanguage;
}

function interpolate(template: string, params?: TranslationParams) {
  if (!params) return template;
  return Object.entries(params).reduce(
    (acc, [key, value]) => acc.replace(new RegExp(`\\{${key}\\}`, "g"), String(value)),
    template
  );
}

export function AppPreferencesProvider({ children }: { children: ReactNode }) {
  const { colorScheme, setColorScheme } = useColorScheme();
  const [theme, setThemeState] = useState<AppTheme>("system");
  const [language, setLanguageState] = useState<AppLanguage>("pt-BR");

  const persist = useCallback(async (value: StoredPreferences) => {
    await AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(value));
  }, []);

  useEffect(() => {
    AsyncStorage.getItem(STORAGE_KEY)
      .then((raw) => {
        if (!raw) {
          // Primeiro uso: idioma segue o aparelho do cliente
          const deviceLang = Localization.getLocales()?.[0]?.languageCode ?? "en";
          const detected: AppLanguage =
            deviceLang === "pt" ? "pt-BR" : deviceLang === "es" ? "es" : "en-US";
          setLanguageState(detected);
          return;
        }
        const parsed = JSON.parse(raw) as Partial<StoredPreferences>;
        if (parsed.theme === "light" || parsed.theme === "dark" || parsed.theme === "system") {
          setThemeState(parsed.theme);
          setColorScheme(parsed.theme);
        }
        if (parsed.language === "pt-BR" || parsed.language === "en-US" || parsed.language === "es") {
          setLanguageState(parsed.language);
        }
      })
      .catch(() => {
        // Falhas de leitura de preferencia nao podem bloquear o app.
      });
  }, [setColorScheme]);

  useEffect(() => {
    setColorScheme(theme);
  }, [setColorScheme, theme]);

  const setTheme = useCallback(
    async (nextTheme: AppTheme) => {
      setThemeState(nextTheme);
      setColorScheme(nextTheme);
      await persist({ theme: nextTheme, language });
    },
    [language, persist, setColorScheme]
  );

  const setLanguage = useCallback(
    async (nextLanguage: AppLanguage) => {
      setLanguageState(nextLanguage);
      await persist({ theme, language: nextLanguage });
    },
    [persist, theme]
  );

  const t = useCallback(
    (key: string, params?: TranslationParams) => {
      const table = dictionaries[language] ?? dictionaries["pt-BR"];
      const phrase = table[key] ?? dictionaries["pt-BR"][key] ?? key;
      return interpolate(phrase, params);
    },
    [language]
  );

  const isDark = (theme === "system" ? colorScheme : theme) === "dark";

  const value = useMemo(
    () => ({
      theme,
      language,
      isDark,
      setTheme,
      setLanguage,
      t,
    }),
    [theme, language, isDark, setTheme, setLanguage, t]
  );

  return (
    <AppPreferencesContext.Provider value={value}>
      {children}
    </AppPreferencesContext.Provider>
  );
}

export function useAppPreferences() {
  const ctx = useContext(AppPreferencesContext);
  if (!ctx) {
    throw new Error("useAppPreferences deve ser usado dentro de <AppPreferencesProvider>");
  }
  return ctx;
}
